// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/therobertcrocker/gm-toolkit/internal/faction/engine (interfaces: InputCollector)
//
// Generated by this command:
//
//	mockgen -destination=internal/faction/engine/action/actions/mocks/mock_collector.go -package=mocks github.com/therobertcrocker/gm-toolkit/internal/faction/engine InputCollector
//

// Package mocks is a generated GoMock package.
package mocks

import (
	reflect "reflect"

	domain "github.com/therobertcrocker/gm-toolkit/internal/faction/domain"
	action "github.com/therobertcrocker/gm-toolkit/internal/faction/engine/action"
	hooks "github.com/therobertcrocker/gm-toolkit/internal/faction/engine/hooks"
	rulebook "github.com/therobertcrocker/gm-toolkit/internal/faction/rulebook"
	state "github.com/therobertcrocker/gm-toolkit/internal/faction/state"
	gomock "go.uber.org/mock/gomock"
)

// MockInputCollector is a mock of InputCollector interface.
type MockInputCollector struct {
	ctrl     *gomock.Controller
	recorder *MockInputCollectorMockRecorder
	isgomock struct{}
}

// MockInputCollectorMockRecorder is the mock recorder for MockInputCollector.
type MockInputCollectorMockRecorder struct {
	mock *MockInputCollector
}

// NewMockInputCollector creates a new mock instance.
func NewMockInputCollector(ctrl *gomock.Controller) *MockInputCollector {
	mock := &MockInputCollector{ctrl: ctrl}
	mock.recorder = &MockInputCollectorMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockInputCollector) EXPECT() *MockInputCollectorMockRecorder {
	return m.recorder
}

// AwaitCheckpoint mocks base method.
func (m *MockInputCollector) AwaitCheckpoint(phase string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "AwaitCheckpoint", phase)
	ret0, _ := ret[0].(error)
	return ret0
}

// AwaitCheckpoint indicates an expected call of AwaitCheckpoint.
func (mr *MockInputCollectorMockRecorder) AwaitCheckpoint(phase any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AwaitCheckpoint", reflect.TypeOf((*MockInputCollector)(nil).AwaitCheckpoint), phase)
}

// ConfirmAbilityApplied mocks base method.
func (m *MockInputCollector) ConfirmAbilityApplied(asset *domain.Asset, def *domain.AssetDefinition) (bool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ConfirmAbilityApplied", asset, def)
	ret0, _ := ret[0].(bool)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ConfirmAbilityApplied indicates an expected call of ConfirmAbilityApplied.
func (mr *MockInputCollectorMockRecorder) ConfirmAbilityApplied(asset, def any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ConfirmAbilityApplied", reflect.TypeOf((*MockInputCollector)(nil).ConfirmAbilityApplied), asset, def)
}

// ConfirmRedirectToBase mocks base method.
func (m *MockInputCollector) ConfirmRedirectToBase(defenderFaction *domain.Faction, base *domain.Base, damage int) (bool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ConfirmRedirectToBase", defenderFaction, base, damage)
	ret0, _ := ret[0].(bool)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ConfirmRedirectToBase indicates an expected call of ConfirmRedirectToBase.
func (mr *MockInputCollectorMockRecorder) ConfirmRedirectToBase(defenderFaction, base, damage any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ConfirmRedirectToBase", reflect.TypeOf((*MockInputCollector)(nil).ConfirmRedirectToBase), defenderFaction, base, damage)
}

// ConfirmReroll mocks base method.
func (m *MockInputCollector) ConfirmReroll(directive hooks.RerollDirective) bool {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ConfirmReroll", directive)
	ret0, _ := ret[0].(bool)
	return ret0
}

// ConfirmReroll indicates an expected call of ConfirmReroll.
func (mr *MockInputCollectorMockRecorder) ConfirmReroll(directive any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ConfirmReroll", reflect.TypeOf((*MockInputCollector)(nil).ConfirmReroll), directive)
}

// ConfirmRivalFreeAttack mocks base method.
func (m *MockInputCollector) ConfirmRivalFreeAttack(rival *domain.Faction, rivalRoll, factionRoll int) (bool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ConfirmRivalFreeAttack", rival, rivalRoll, factionRoll)
	ret0, _ := ret[0].(bool)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ConfirmRivalFreeAttack indicates an expected call of ConfirmRivalFreeAttack.
func (mr *MockInputCollectorMockRecorder) ConfirmRivalFreeAttack(rival, rivalRoll, factionRoll any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ConfirmRivalFreeAttack", reflect.TypeOf((*MockInputCollector)(nil).ConfirmRivalFreeAttack), rival, rivalRoll, factionRoll)
}

// SelectAbilityAssets mocks base method.
func (m *MockInputCollector) SelectAbilityAssets(faction *domain.Faction, candidates []*domain.Asset, arg2 *rulebook.Rulebook) ([]*domain.Asset, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SelectAbilityAssets", faction, candidates, arg2)
	ret0, _ := ret[0].([]*domain.Asset)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// SelectAbilityAssets indicates an expected call of SelectAbilityAssets.
func (mr *MockInputCollectorMockRecorder) SelectAbilityAssets(faction, candidates, arg2 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SelectAbilityAssets", reflect.TypeOf((*MockInputCollector)(nil).SelectAbilityAssets), faction, candidates, arg2)
}

// SelectAction mocks base method.
func (m *MockInputCollector) SelectAction(faction *domain.Faction, available []action.Action) (action.Action, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SelectAction", faction, available)
	ret0, _ := ret[0].(action.Action)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// SelectAction indicates an expected call of SelectAction.
func (mr *MockInputCollectorMockRecorder) SelectAction(faction, available any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SelectAction", reflect.TypeOf((*MockInputCollector)(nil).SelectAction), faction, available)
}

// SelectAsset mocks base method.
func (m *MockInputCollector) SelectAsset(assets []*domain.Asset, arg1 *rulebook.Rulebook) (*domain.Asset, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SelectAsset", assets, arg1)
	ret0, _ := ret[0].(*domain.Asset)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// SelectAsset indicates an expected call of SelectAsset.
func (mr *MockInputCollectorMockRecorder) SelectAsset(assets, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SelectAsset", reflect.TypeOf((*MockInputCollector)(nil).SelectAsset), assets, arg1)
}

// SelectAttackers mocks base method.
func (m *MockInputCollector) SelectAttackers(eligible []*domain.Asset, arg1 *rulebook.Rulebook) ([]*domain.Asset, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SelectAttackers", eligible, arg1)
	ret0, _ := ret[0].([]*domain.Asset)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// SelectAttackers indicates an expected call of SelectAttackers.
func (mr *MockInputCollectorMockRecorder) SelectAttackers(eligible, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SelectAttackers", reflect.TypeOf((*MockInputCollector)(nil).SelectAttackers), eligible, arg1)
}

// SelectBaseAttackers mocks base method.
func (m *MockInputCollector) SelectBaseAttackers(rival *domain.Faction, eligible []*domain.Asset, arg2 *rulebook.Rulebook) ([]*domain.Asset, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SelectBaseAttackers", rival, eligible, arg2)
	ret0, _ := ret[0].([]*domain.Asset)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// SelectBaseAttackers indicates an expected call of SelectBaseAttackers.
func (mr *MockInputCollectorMockRecorder) SelectBaseAttackers(rival, eligible, arg2 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SelectBaseAttackers", reflect.TypeOf((*MockInputCollector)(nil).SelectBaseAttackers), rival, eligible, arg2)
}

// SelectBribeTarget mocks base method.
func (m *MockInputCollector) SelectBribeTarget(faction *domain.Faction, factionState *state.FactionState) (*domain.Base, int, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SelectBribeTarget", faction, factionState)
	ret0, _ := ret[0].(*domain.Base)
	ret1, _ := ret[1].(int)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// SelectBribeTarget indicates an expected call of SelectBribeTarget.
func (mr *MockInputCollectorMockRecorder) SelectBribeTarget(faction, factionState any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SelectBribeTarget", reflect.TypeOf((*MockInputCollector)(nil).SelectBribeTarget), faction, factionState)
}

// SelectBuyOrder mocks base method.
func (m *MockInputCollector) SelectBuyOrder(worlds []string, purchasable []*domain.AssetDefinition) (action.BuyOrder, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SelectBuyOrder", worlds, purchasable)
	ret0, _ := ret[0].(action.BuyOrder)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// SelectBuyOrder indicates an expected call of SelectBuyOrder.
func (mr *MockInputCollectorMockRecorder) SelectBuyOrder(worlds, purchasable any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SelectBuyOrder", reflect.TypeOf((*MockInputCollector)(nil).SelectBuyOrder), worlds, purchasable)
}

// SelectDefender mocks base method.
func (m *MockInputCollector) SelectDefender(attacker *domain.Asset, eligible []*domain.Asset, arg2 *rulebook.Rulebook) (*domain.Asset, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SelectDefender", attacker, eligible, arg2)
	ret0, _ := ret[0].(*domain.Asset)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// SelectDefender indicates an expected call of SelectDefender.
func (mr *MockInputCollectorMockRecorder) SelectDefender(attacker, eligible, arg2 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SelectDefender", reflect.TypeOf((*MockInputCollector)(nil).SelectDefender), attacker, eligible, arg2)
}

// SelectExpandInfluenceOrder mocks base method.
func (m *MockInputCollector) SelectExpandInfluenceOrder(faction *domain.Faction, factionState *state.FactionState) (action.ExpandInfluenceOrder, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SelectExpandInfluenceOrder", faction, factionState)
	ret0, _ := ret[0].(action.ExpandInfluenceOrder)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// SelectExpandInfluenceOrder indicates an expected call of SelectExpandInfluenceOrder.
func (mr *MockInputCollectorMockRecorder) SelectExpandInfluenceOrder(faction, factionState any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SelectExpandInfluenceOrder", reflect.TypeOf((*MockInputCollector)(nil).SelectExpandInfluenceOrder), faction, factionState)
}

// SelectFactionTestTarget mocks base method.
func (m *MockInputCollector) SelectFactionTestTarget(asset *domain.Asset, effect domain.AbilityEffectType, candidates []*domain.Faction) (*domain.Faction, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SelectFactionTestTarget", asset, effect, candidates)
	ret0, _ := ret[0].(*domain.Faction)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// SelectFactionTestTarget indicates an expected call of SelectFactionTestTarget.
func (mr *MockInputCollectorMockRecorder) SelectFactionTestTarget(asset, effect, candidates any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SelectFactionTestTarget", reflect.TypeOf((*MockInputCollector)(nil).SelectFactionTestTarget), asset, effect, candidates)
}

// SelectModifiers mocks base method.
func (m *MockInputCollector) SelectModifiers(offers []hooks.ModifierOffer) []hooks.ModifierOffer {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SelectModifiers", offers)
	ret0, _ := ret[0].([]hooks.ModifierOffer)
	return ret0
}

// SelectModifiers indicates an expected call of SelectModifiers.
func (mr *MockInputCollectorMockRecorder) SelectModifiers(offers any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SelectModifiers", reflect.TypeOf((*MockInputCollector)(nil).SelectModifiers), offers)
}

// SelectMoveDestination mocks base method.
func (m *MockInputCollector) SelectMoveDestination(asset *domain.Asset, worlds []string) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SelectMoveDestination", asset, worlds)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// SelectMoveDestination indicates an expected call of SelectMoveDestination.
func (mr *MockInputCollectorMockRecorder) SelectMoveDestination(asset, worlds any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SelectMoveDestination", reflect.TypeOf((*MockInputCollector)(nil).SelectMoveDestination), asset, worlds)
}

// SelectRefitOrder mocks base method.
func (m *MockInputCollector) SelectRefitOrder(options []action.RefitOption, arg1 *rulebook.Rulebook) (action.RefitOrder, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SelectRefitOrder", options, arg1)
	ret0, _ := ret[0].(action.RefitOrder)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// SelectRefitOrder indicates an expected call of SelectRefitOrder.
func (mr *MockInputCollectorMockRecorder) SelectRefitOrder(options, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SelectRefitOrder", reflect.TypeOf((*MockInputCollector)(nil).SelectRefitOrder), options, arg1)
}

// SelectRepairOrders mocks base method.
func (m *MockInputCollector) SelectRepairOrders(faction *domain.Faction, damaged []*domain.Asset, arg2 *rulebook.Rulebook) ([]action.RepairOrder, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SelectRepairOrders", faction, damaged, arg2)
	ret0, _ := ret[0].([]action.RepairOrder)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// SelectRepairOrders indicates an expected call of SelectRepairOrders.
func (mr *MockInputCollectorMockRecorder) SelectRepairOrders(faction, damaged, arg2 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SelectRepairOrders", reflect.TypeOf((*MockInputCollector)(nil).SelectRepairOrders), faction, damaged, arg2)
}

// SelectSeizeTarget mocks base method.
func (m *MockInputCollector) SelectSeizeTarget(faction *domain.Faction, factionState *state.FactionState) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SelectSeizeTarget", faction, factionState)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// SelectSeizeTarget indicates an expected call of SelectSeizeTarget.
func (mr *MockInputCollectorMockRecorder) SelectSeizeTarget(faction, factionState any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SelectSeizeTarget", reflect.TypeOf((*MockInputCollector)(nil).SelectSeizeTarget), faction, factionState)
}
