// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/therobertcrocker/gm-toolkit/internal/faction/engine/action (interfaces: Collector)
//
// Generated by this command:
//
//	mockgen -destination=actions/mocks/mock_collector.go -package=mocks github.com/therobertcrocker/gm-toolkit/internal/faction/engine/action Collector
//

// Package mocks is a generated GoMock package.
package mocks

import (
	reflect "reflect"

	domain "github.com/therobertcrocker/gm-toolkit/internal/faction/domain"
	action "github.com/therobertcrocker/gm-toolkit/internal/faction/engine/action"
	hooks "github.com/therobertcrocker/gm-toolkit/internal/faction/engine/hooks"
	rulebook "github.com/therobertcrocker/gm-toolkit/internal/faction/rulebook"
	state "github.com/therobertcrocker/gm-toolkit/internal/faction/state"
	gomock "go.uber.org/mock/gomock"
)

// MockCollector is a mock of Collector interface.
type MockCollector struct {
	ctrl     *gomock.Controller
	recorder *MockCollectorMockRecorder
	isgomock struct{}
}

// MockCollectorMockRecorder is the mock recorder for MockCollector.
type MockCollectorMockRecorder struct {
	mock *MockCollector
}

// NewMockCollector creates a new mock instance.
func NewMockCollector(ctrl *gomock.Controller) *MockCollector {
	mock := &MockCollector{ctrl: ctrl}
	mock.recorder = &MockCollectorMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockCollector) EXPECT() *MockCollectorMockRecorder {
	return m.recorder
}

// ConfirmAbilityApplied mocks base method.
func (m *MockCollector) ConfirmAbilityApplied(asset *domain.Asset, def *domain.AssetDefinition) (bool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ConfirmAbilityApplied", asset, def)
	ret0, _ := ret[0].(bool)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ConfirmAbilityApplied indicates an expected call of ConfirmAbilityApplied.
func (mr *MockCollectorMockRecorder) ConfirmAbilityApplied(asset, def any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ConfirmAbilityApplied", reflect.TypeOf((*MockCollector)(nil).ConfirmAbilityApplied), asset, def)
}

// ConfirmRedirectToBase mocks base method.
func (m *MockCollector) ConfirmRedirectToBase(defenderFaction *domain.Faction, base *domain.Base, damage int) (bool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ConfirmRedirectToBase", defenderFaction, base, damage)
	ret0, _ := ret[0].(bool)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ConfirmRedirectToBase indicates an expected call of ConfirmRedirectToBase.
func (mr *MockCollectorMockRecorder) ConfirmRedirectToBase(defenderFaction, base, damage any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ConfirmRedirectToBase", reflect.TypeOf((*MockCollector)(nil).ConfirmRedirectToBase), defenderFaction, base, damage)
}

// ConfirmReroll mocks base method.
func (m *MockCollector) ConfirmReroll(directive hooks.RerollDirective) bool {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ConfirmReroll", directive)
	ret0, _ := ret[0].(bool)
	return ret0
}

// ConfirmReroll indicates an expected call of ConfirmReroll.
func (mr *MockCollectorMockRecorder) ConfirmReroll(directive any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ConfirmReroll", reflect.TypeOf((*MockCollector)(nil).ConfirmReroll), directive)
}

// ConfirmRivalFreeAttack mocks base method.
func (m *MockCollector) ConfirmRivalFreeAttack(rival *domain.Faction, rivalRoll, factionRoll int) (bool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ConfirmRivalFreeAttack", rival, rivalRoll, factionRoll)
	ret0, _ := ret[0].(bool)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ConfirmRivalFreeAttack indicates an expected call of ConfirmRivalFreeAttack.
func (mr *MockCollectorMockRecorder) ConfirmRivalFreeAttack(rival, rivalRoll, factionRoll any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ConfirmRivalFreeAttack", reflect.TypeOf((*MockCollector)(nil).ConfirmRivalFreeAttack), rival, rivalRoll, factionRoll)
}

// SelectAbilityAssets mocks base method.
func (m *MockCollector) SelectAbilityAssets(faction *domain.Faction, candidates []*domain.Asset, arg2 *rulebook.Rulebook) ([]*domain.Asset, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SelectAbilityAssets", faction, candidates, arg2)
	ret0, _ := ret[0].([]*domain.Asset)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// SelectAbilityAssets indicates an expected call of SelectAbilityAssets.
func (mr *MockCollectorMockRecorder) SelectAbilityAssets(faction, candidates, arg2 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SelectAbilityAssets", reflect.TypeOf((*MockCollector)(nil).SelectAbilityAssets), faction, candidates, arg2)
}

// SelectAsset mocks base method.
func (m *MockCollector) SelectAsset(assets []*domain.Asset, arg1 *rulebook.Rulebook) (*domain.Asset, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SelectAsset", assets, arg1)
	ret0, _ := ret[0].(*domain.Asset)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// SelectAsset indicates an expected call of SelectAsset.
func (mr *MockCollectorMockRecorder) SelectAsset(assets, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SelectAsset", reflect.TypeOf((*MockCollector)(nil).SelectAsset), assets, arg1)
}

// SelectAttackers mocks base method.
func (m *MockCollector) SelectAttackers(eligible []*domain.Asset, arg1 *rulebook.Rulebook) ([]*domain.Asset, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SelectAttackers", eligible, arg1)
	ret0, _ := ret[0].([]*domain.Asset)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// SelectAttackers indicates an expected call of SelectAttackers.
func (mr *MockCollectorMockRecorder) SelectAttackers(eligible, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SelectAttackers", reflect.TypeOf((*MockCollector)(nil).SelectAttackers), eligible, arg1)
}

// SelectBaseAttackers mocks base method.
func (m *MockCollector) SelectBaseAttackers(rival *domain.Faction, eligible []*domain.Asset, arg2 *rulebook.Rulebook) ([]*domain.Asset, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SelectBaseAttackers", rival, eligible, arg2)
	ret0, _ := ret[0].([]*domain.Asset)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// SelectBaseAttackers indicates an expected call of SelectBaseAttackers.
func (mr *MockCollectorMockRecorder) SelectBaseAttackers(rival, eligible, arg2 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SelectBaseAttackers", reflect.TypeOf((*MockCollector)(nil).SelectBaseAttackers), rival, eligible, arg2)
}

// SelectBribeTarget mocks base method.
func (m *MockCollector) SelectBribeTarget(faction *domain.Faction, factionState *state.FactionState) (*domain.Base, int, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SelectBribeTarget", faction, factionState)
	ret0, _ := ret[0].(*domain.Base)
	ret1, _ := ret[1].(int)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// SelectBribeTarget indicates an expected call of SelectBribeTarget.
func (mr *MockCollectorMockRecorder) SelectBribeTarget(faction, factionState any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SelectBribeTarget", reflect.TypeOf((*MockCollector)(nil).SelectBribeTarget), faction, factionState)
}

// SelectBuyOrder mocks base method.
func (m *MockCollector) SelectBuyOrder(purchasablePerWorld map[string][]*domain.AssetDefinition) (action.BuyOrder, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SelectBuyOrder", purchasablePerWorld)
	ret0, _ := ret[0].(action.BuyOrder)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// SelectBuyOrder indicates an expected call of SelectBuyOrder.
func (mr *MockCollectorMockRecorder) SelectBuyOrder(purchasablePerWorld any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SelectBuyOrder", reflect.TypeOf((*MockCollector)(nil).SelectBuyOrder), purchasablePerWorld)
}

// SelectChangeHomeworldTarget mocks base method.
func (m *MockCollector) SelectChangeHomeworldTarget(faction *domain.Faction, factionState *state.FactionState) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SelectChangeHomeworldTarget", faction, factionState)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// SelectChangeHomeworldTarget indicates an expected call of SelectChangeHomeworldTarget.
func (mr *MockCollectorMockRecorder) SelectChangeHomeworldTarget(faction, factionState any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SelectChangeHomeworldTarget", reflect.TypeOf((*MockCollector)(nil).SelectChangeHomeworldTarget), faction, factionState)
}

// SelectDefender mocks base method.
func (m *MockCollector) SelectDefender(attacker *domain.Asset, eligible []*domain.Asset, arg2 *rulebook.Rulebook) (*domain.Asset, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SelectDefender", attacker, eligible, arg2)
	ret0, _ := ret[0].(*domain.Asset)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// SelectDefender indicates an expected call of SelectDefender.
func (mr *MockCollectorMockRecorder) SelectDefender(attacker, eligible, arg2 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SelectDefender", reflect.TypeOf((*MockCollector)(nil).SelectDefender), attacker, eligible, arg2)
}

// SelectExpandInfluenceOrder mocks base method.
func (m *MockCollector) SelectExpandInfluenceOrder(faction *domain.Faction, factionState *state.FactionState, eligibleNewBaseWorlds []string) (action.ExpandInfluenceOrder, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SelectExpandInfluenceOrder", faction, factionState, eligibleNewBaseWorlds)
	ret0, _ := ret[0].(action.ExpandInfluenceOrder)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// SelectExpandInfluenceOrder indicates an expected call of SelectExpandInfluenceOrder.
func (mr *MockCollectorMockRecorder) SelectExpandInfluenceOrder(faction, factionState, eligibleNewBaseWorlds any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SelectExpandInfluenceOrder", reflect.TypeOf((*MockCollector)(nil).SelectExpandInfluenceOrder), faction, factionState, eligibleNewBaseWorlds)
}

// SelectFactionTestTarget mocks base method.
func (m *MockCollector) SelectFactionTestTarget(asset *domain.Asset, effect domain.AbilityEffectType, candidates []*domain.Faction) (*domain.Faction, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SelectFactionTestTarget", asset, effect, candidates)
	ret0, _ := ret[0].(*domain.Faction)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// SelectFactionTestTarget indicates an expected call of SelectFactionTestTarget.
func (mr *MockCollectorMockRecorder) SelectFactionTestTarget(asset, effect, candidates any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SelectFactionTestTarget", reflect.TypeOf((*MockCollector)(nil).SelectFactionTestTarget), asset, effect, candidates)
}

// SelectModifiers mocks base method.
func (m *MockCollector) SelectModifiers(offers []hooks.ModifierOffer) []hooks.ModifierOffer {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SelectModifiers", offers)
	ret0, _ := ret[0].([]hooks.ModifierOffer)
	return ret0
}

// SelectModifiers indicates an expected call of SelectModifiers.
func (mr *MockCollectorMockRecorder) SelectModifiers(offers any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SelectModifiers", reflect.TypeOf((*MockCollector)(nil).SelectModifiers), offers)
}

// SelectRefitOrder mocks base method.
func (m *MockCollector) SelectRefitOrder(options []action.RefitOption, arg1 *rulebook.Rulebook) (action.RefitOrder, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SelectRefitOrder", options, arg1)
	ret0, _ := ret[0].(action.RefitOrder)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// SelectRefitOrder indicates an expected call of SelectRefitOrder.
func (mr *MockCollectorMockRecorder) SelectRefitOrder(options, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SelectRefitOrder", reflect.TypeOf((*MockCollector)(nil).SelectRefitOrder), options, arg1)
}

// SelectRepairOrders mocks base method.
func (m *MockCollector) SelectRepairOrders(faction *domain.Faction, damaged []*domain.Asset, arg2 *rulebook.Rulebook) ([]action.RepairOrder, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SelectRepairOrders", faction, damaged, arg2)
	ret0, _ := ret[0].([]action.RepairOrder)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// SelectRepairOrders indicates an expected call of SelectRepairOrders.
func (mr *MockCollectorMockRecorder) SelectRepairOrders(faction, damaged, arg2 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SelectRepairOrders", reflect.TypeOf((*MockCollector)(nil).SelectRepairOrders), faction, damaged, arg2)
}

// SelectSeizeTarget mocks base method.
func (m *MockCollector) SelectSeizeTarget(faction *domain.Faction, factionState *state.FactionState) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SelectSeizeTarget", faction, factionState)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// SelectSeizeTarget indicates an expected call of SelectSeizeTarget.
func (mr *MockCollectorMockRecorder) SelectSeizeTarget(faction, factionState any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SelectSeizeTarget", reflect.TypeOf((*MockCollector)(nil).SelectSeizeTarget), faction, factionState)
}
